.Dd August 31, 2014
.Dt gzipfinfo
.Os libgzipf
.Sh NAME
.Nm gzipfinfo
.Nd determines information about a GZIP file
.Sh SYNOPSIS
.Nm gzipfinfo
.Op Fl hvV
.Va Ar source
.Sh DESCRIPTION
.Nm gzipfinfo
is a utility to determine information about a GZIP file
.Pp
.Nm gzipfinfo
is part of the
.Nm libgzipf
package.
.Nm libgzipf
is a library to access the GZIP file format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# gzipfinfo file.gz
gzipfinfo 20190717

...

.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
https://github.com/libyal/libgzipf/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (C) 2019-2022, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
